- build.cake
- nuget/TestCentric.Engine.nuspec
- src/TestEngine/agents/testcentric-agent/testcentric-agent.csproj
- src/TestEngine/testcentric.engine.tests/Services/AgentLauncherTests.cs
- src/TestEngine/testcentric.engine.tests/Services/RuntimeFrameworkServiceTests.cs
- src/TestEngine/testcentric.engine.tests/Services/TestAgencyTests.cs
- src/TestEngine/testcentric.engine.tests/Services/TestAgentServiceTests.cs
- src/TestEngine/testcentric.engine/Services/AgentLaunchers/Net20AgentLauncher.cs
- src/TestEngine/testcentric.engine/Services/TestAgency.cs
> Eliminate net20 agent

- src/TestEngine/mock-assembly/mock-assembly.csproj
- src/TestEngine/notest-assembly/notest-assembly.csproj
- src/TestEngine/testcentric.engine.core.tests/testcentric.engine.core.tests.csproj
- testcentric-engine.sln
> Stop making eol check for .NET Core 2.1

- src/TestBed/ResultReporter.cs
- src/TestBed/TestEventHandler.cs
- src/TestBed/TestRunner.cs
- src/TestEngine/testcentric.engine.tests/Services/RuntimeFrameworkServiceTests.cs
- src/TestEngine/testcentric.engine/Runtime.cs
- src/TestEngine/testcentric.engine/Services/TestAgency.cs
> Cleaner error handling when user tries to run a .NET Standard test assembly

- src/TestEngine/testcentric.engine.api/testcentric.engine.api.csproj
- src/TestEngine/testcentric.engine.core.tests/testcentric.engine.core.tests.csproj
- src/TestEngine/testcentric.engine.core/testcentric.engine.core.csproj
- src/TestEngine/testcentric.engine.tests/testcentric.engine.tests.csproj
- src/TestEngine/testcentric.engine/testcentric.engine.csproj
> Use latest dev build of nunit.engine.api

- src/TestBed/ResultReporter.cs
- src/TestBed/ResultSummary.cs
- src/TestBed/TestEventHandler.cs
- src/TestEngine/testcentric.engine.core/Runners/TestAgentRunner.cs
> Improve  TestRunner and provide better message for no driver found

- cake/package-tests.cake
- cake/test-reports.cake
- cake/test-results.cake
- src/TestBed/TestRunner.cs
- src/TestEngine/testcentric.engine.core/EnginePackageSettings.cs
- src/TestEngine/testcentric.engine/Services/TestAgency.cs
> Add package setting for agent actually used

- cake/package-tests.cake
- src/TestEngine/Directory.Build.props
- src/TestEngine/mock-assembly/mock-assembly.csproj
- src/TestEngine/notest-assembly/notest-assembly.csproj
- src/TestEngine/testcentric.engine.api/testcentric.engine.api.csproj
- src/TestEngine/testcentric.engine.core.tests/testcentric.engine.core.tests.csproj
- src/TestEngine/testcentric.engine.core/testcentric.engine.core.csproj
- src/TestEngine/testcentric.engine.tests/testcentric.engine.tests.csproj
- src/TestEngine/testcentric.engine/testcentric.engine.csproj
> Set version of packaged assemblies correctly

- cake/package-tests.cake
> Reinstate test using Net20PluggableAgent extension

- src/TestEngine/testcentric.engine.core/Drivers/NUnitNetStandardDriver.cs
> Throw exception for NetStandard framework driver StopRun(true)

- src/TestBed/CommandLineOptions.cs
- src/TestBed/TestBed.cs
- src/TestEngine/hung-tests/FastFixture.cs
- src/TestEngine/hung-tests/HangingFixture.cs
- src/TestEngine/hung-tests/Properties/AssemblyInfo.cs
- src/TestEngine/hung-tests/SlowFixture.cs
- src/TestEngine/hung-tests/hung-tests.csproj
- src/TestEngine/testcentric.engine.core/Agents/RemoteTestAgent.cs
- src/TestEngine/testcentric.engine/Runners/AssemblyRunner.cs
- testcentric-engine.sln
> Cancel process in lieu of StopRun(true)

- src/TestBed/CommandLineOptions.cs
- src/TestBed/TestBed.cs
- src/TestEngine/testcentric.engine/Services/TestEventDispatcher.cs
- src/TestEngine/testcentric.engine/Services/WorkItemTracker.cs
> Fix deadlock problem in WorkItemTracker

- src/TestBed/CommandLineOptions.cs
- src/TestBed/ResultReporter.cs
- src/TestBed/TestBed.cs
- src/TestBed/TestEventHandler.cs
- src/TestEngine/testcentric.engine.core/Agents/AgentExitCodes.cs
- src/TestEngine/testcentric.engine.core/Communication/Transports/Tcp/TestAgentTcpTransport.cs
- src/TestEngine/testcentric.engine.core/Drivers/NUnit3FrameworkDriver.cs
- src/TestEngine/testcentric.engine.core/Drivers/NUnitNetStandardDriver.cs
- src/TestEngine/testcentric.engine.core/Runners/TestAgentRunner.cs
- src/TestEngine/testcentric.engine.tests/Services/WorkItemTrackerTests.cs
- src/TestEngine/testcentric.engine/Runners/AssemblyRunner.cs
- src/TestEngine/testcentric.engine/Runners/MasterTestRunner.cs
- src/TestEngine/testcentric.engine/Services/TestAgency.cs
- src/TestEngine/testcentric.engine/Services/TestEventDispatcher.cs
- src/TestEngine/testcentric.engine/Services/WorkItemTracker.cs
> Another revision of handling forced stop - Exit from TestAgentRunner

- src/TestEngine/testcentric.engine/Runners/MasterTestRunner.cs
- src/TestEngine/testcentric.engine/Services/TestEventDispatcher.cs
> Ensure that test-run element is sent when test is cancelled

- src/TestEngine/testcentric.engine.core/Internal/XmlHelper.cs
- src/TestEngine/testcentric.engine/Internal/ResultHelper.cs
- src/TestEngine/testcentric.engine/Runners/MasterTestRunner.cs
- src/TestEngine/testcentric.engine/Services/TestEventDispatcher.cs
- src/TestEngine/testcentric.engine/Services/WorkItemTracker.cs
> Further restructuring of dispatcher; set test not running before run finished notice

- src/TestEngine/testcentric.engine.core.tests/Internal/TestFilterExtensionTests.cs
- src/TestEngine/testcentric.engine.core.tests/Properties/launchSettings.json
- src/TestEngine/testcentric.engine.core/Internal/TestFilterExtensions.cs
- src/TestEngine/testcentric.engine.core/Runners/TestAgentRunner.cs
> Don't run assemblies if the filter cannot possibly succeed

- cake/package-tests.cake
- src/TestEngine/testcentric.engine.api/testcentric.engine.api.csproj
- src/TestEngine/testcentric.engine.core.tests/testcentric.engine.core.tests.csproj
- src/TestEngine/testcentric.engine.core/testcentric.engine.core.csproj
- src/TestEngine/testcentric.engine.tests/Runners/NonRunnableAssemblyRunnerTests.cs
- src/TestEngine/testcentric.engine.tests/TestPackageBuilder.cs
- src/TestEngine/testcentric.engine.tests/testcentric.engine.tests.csproj
- src/TestEngine/testcentric.engine/testcentric.engine.csproj
- src/TestEngine/testcentric.extensibility.tests/testcentric.extensibility.tests.csproj
- src/TestEngine/testcentric.extensibility/ExtensionManager.cs
- src/TestEngine/testcentric.extensibility/testcentric.extensibility.csproj
> Return to use of the NUnit 3 API rather than NUnit 4, which is not yet in production

- appveyor.yml
- build.cake
- cake/package-tests.cake
- cake/parameters.cake
- nuget/TestCentric.Engine.nuspec
- src/TestEngine/agents/testcentric-agent/testcentric-agent.csproj
- src/TestEngine/aspnetcore-test/aspnetcore-test.csproj
- src/TestEngine/mock-assembly/mock-assembly.csproj
- src/TestEngine/testcentric.engine.tests/Services/TestAgencyTests.cs
- src/TestEngine/testcentric.engine.tests/Services/TestAgentServiceTests.cs
- src/TestEngine/testcentric.engine/Services/AgentLaunchers/Net60AgentLauncher.cs
- src/TestEngine/testcentric.engine/Services/TestAgency.cs
- src/TestEngine/windows-forms-test/windows-forms-test.csproj
> Add .NET 6.0 agent

- build.cake
- cake/package-tests.cake
- cake/parameters.cake
- nuget/TestCentric.Engine.nuspec
- src/TestEngine/agents/testcentric-agent/testcentric-agent.csproj
- src/TestEngine/aspnetcore-test/aspnetcore-test.csproj
- src/TestEngine/mock-assembly/mock-assembly.csproj
- src/TestEngine/testcentric.engine.tests/Services/TestAgencyTests.cs
- src/TestEngine/testcentric.engine.tests/Services/TestAgentServiceTests.cs
- src/TestEngine/testcentric.engine/Services/AgentLaunchers/Net70AgentLauncher.cs
- src/TestEngine/testcentric.engine/Services/TestAgency.cs
- src/TestEngine/windows-forms-test/windows-forms-test.csproj
> Add .NET 7.0 agent

- cake/package-tests.cake
- nuget/TestCentric.Engine.nuspec
- src/TestEngine/agents/testcentric-agent/testcentric-agent.csproj
> Fix CI build packaging

- src/TestEngine/testcentric.extensibility/ExtensionManager.cs
> Eliminate unexpected exception in ExtensionManager

- appveyor.yml
- cake/parameters.cake
> Use TestCentric-specific names for environment variables

- cake/package-tests.cake
> Specify verson of extensions used in build script

- src/TestEngine/testcentric.engine.core/Internal/TestAssemblyResolver.cs
> Handle preview runtime installs correctly

- cake/build-settings.cake
> Add local-only test using .NET 8.0 pluggable agent

- src/TestEngine/testcentric.engine.core/testcentric.engine.core.csproj
- src/TestEngine/testcentric.engine/testcentric.engine.csproj
- src/TestEngine/testcentric.extensibility/testcentric.extensibility.csproj
> Update TestCentric.Metadata to version 2.0.0

- cake/build-settings.cake
- nuget/TestCentric.Engine.Api.nuspec
- src/TestEngine/testcentric.engine.api/Extensibility/IAgentLauncher.cs
- src/TestEngine/testcentric.engine.api/testcentric.engine.api.csproj
> Build API assembly for .NET Standard 2.0 only

- cake/build-settings.cake
- src/TestEngine/testcentric.engine.tests/Services/TestAgencyTests.cs
- src/TestEngine/testcentric.engine.tests/Services/TestAgentServiceTests.cs
- src/TestEngine/testcentric.engine/Services/AgentLaunchers/Net462AgentLauncher.cs
- src/TestEngine/testcentric.engine/Services/TestAgency.cs
Fixes #91 
This PR temporarily the tests of pluggable agents, which will need to be updated.
> Sort agents by target runtime

- build.cake
> Make some package tests run at level 2

- build.cake
> Remove tests of pluggable agents from build

- build.cake
- tools/packages.config
> Test using Net70PluggableAgent

- build.cake
> Add back tests using .NET 6.0 pluggable agent

- build.cake
- src/TestEngine/testcentric.engine/Services/TestAgency.cs
> Restore net462 package tests

- src/TestEngine/testcentric.engine.core/Communication/Transports/Tcp/TestAgentTcpTransport.cs
> Log exceptions on command-loop thread

- src/TestBed/test-bed.addins
- src/TestEngine/testcentric.engine.tests/Services/ExtensionServiceTests.cs
- src/TestEngine/testcentric.engine/Services/ExtensionService.cs
- testcentric-engine.sln
- testcentric.nuget.addins
> Get some of the tests of ExtensionService working - more work required

- src/TestEngine/testcentric.engine.api/Extensibility/IAgentLauncher.cs
- src/TestEngine/testcentric.engine.tests/Services/ExtensionServiceTests.cs
- src/TestEngine/testcentric.engine/Services/ExtensionService.cs
- src/TestEngine/testcentric.engine/testcentric.engine.csproj
> Update testcentric.engine.api; use new api for ExtensionManager

- src/TestEngine/testcentric.engine/Services/ExtensionService.cs
- src/TestEngine/testcentric.engine/Services/ITestAgentProvider.cs
- src/TestEngine/testcentric.engine/Services/ITestFrameworkService.cs
- src/TestEngine/testcentric.engine/Services/ITestRunnerFactory.cs
- src/TestEngine/testcentric.engine/Services/ProjectService.cs
- src/TestEngine/testcentric.engine/Services/ResultService.cs
- src/TestEngine/testcentric.engine/Services/RuntimeFrameworkService.cs
- src/TestEngine/testcentric.engine/Services/TestAgency.cs
- src/TestEngine/testcentric.engine/Services/TestEventDispatcher.cs
- src/TestEngine/testcentric.engine/Services/TestFilterService.cs
- src/TestEngine/testcentric.engine/Services/TestFrameworkService.cs
- src/TestEngine/testcentric.engine/Services/TestPackageAnalyzer.cs
- src/TestEngine/testcentric.engine/Services/TestRunnerFactory.cs
> Make services internal where possible

- src/TestEngine/testcentric.engine/Runners/AbstractTestRunner.cs
- src/TestEngine/testcentric.engine/testcentric.engine.csproj
> Move AbstractTestRunner to the engine

- build.cake
- src/TestBed/CommandLineOptions.cs
- src/TestBed/TestBed.cs
- src/TestEngine/testcentric.engine.tests/RuntimeFrameworkTests.cs
> Add a test that uses the .NET 8.0 Agent

- build.cake
- src/TestEngine/testcentric.engine.tests/Internal/XmlHelperTests.cs
- src/TestEngine/testcentric.engine/Guard.cs
- src/TestEngine/testcentric.engine/Internal/ExceptionHelper.cs
- src/TestEngine/testcentric.engine/Internal/XmlHelper.cs
- src/TestEngine/testcentric.engine/testcentric.engine.csproj
> Add utilities from TestCentric.Engine.Core

- build.cake
- src/TestEngine/testcentric.engine.tests/Communication/Messages/MessageTests.cs
- src/TestEngine/testcentric.engine.tests/Communication/Protocols/BinarySerializationProtocolTests.cs
- src/TestEngine/testcentric.engine.tests/TestUtilities/TestPackageExtensions.cs
- src/TestEngine/testcentric.engine/Communication/Protocols/BinarySerializationProtocol.cs
- src/TestEngine/testcentric.engine/Communication/Transports/Tcp/SocketReader.cs
- src/TestEngine/testcentric.engine/testcentric.engine.csproj
> Move communicatons code from TestCentric.Engine.Core

- src/TestEngine/testcentric.engine.tests/InternalTraceTests.cs
- src/TestEngine/testcentric.engine/TestEngine.cs
> Allow changing InternalTraceLevel on the fly

- build.cake
- src/TestEngine/aspnetcore-test/aspnetcore-test.csproj
- src/TestEngine/hung-tests/hung-tests.csproj
- src/TestEngine/mock-assembly/mock-assembly.csproj
- src/TestEngine/notest-assembly/notest-assembly.csproj
- src/TestEngine/testcentric.engine.tests/Api/ServiceLocatorTests.cs
- src/TestEngine/testcentric.engine.tests/Communication/Transports/Tcp/TcpServerTests.cs
- src/TestEngine/testcentric.engine.tests/RuntimeTests.cs
- src/TestEngine/testcentric.engine.tests/Services/ExtensionServiceTests.cs
- src/TestEngine/testcentric.engine.tests/Services/ResultServiceTests.cs
- src/TestEngine/testcentric.engine.tests/Services/RuntimeFrameworkServiceTests.cs
- src/TestEngine/testcentric.engine.tests/Services/ServiceDependencyTests.cs
- src/TestEngine/testcentric.engine.tests/Services/TestFrameworkServiceTests.cs
- src/TestEngine/testcentric.engine.tests/testcentric.engine.tests.csproj
- src/TestEngine/windows-forms-test/windows-forms-test.csproj
> Test engine using NUnit 4

- build.cake
> Use lib directory for engine binaries

- build.cake
- src/TestEngine/mock-test-event-listener/mock-test-event-listener.csproj
- src/TestEngine/testcentric.engine.tests/Services/Fakes/FakeNUnitTestEventListener.cs
- src/TestEngine/testcentric.engine.tests/Services/Fakes/FakeTestEventListener.cs
- src/TestEngine/testcentric.engine.tests/Services/TestEventDispatcherTests.cs
- src/TestEngine/testcentric.engine/Services/NUnitTestEventListenerWrapper.cs
- src/TestEngine/testcentric.engine/Services/TestEventDispatcher.cs
- src/TestEngine/testcentric.engine/testcentric.engine.csproj
> Handle NUnit Test event listeners correctly

- .github/workflows/testcentric-engine-ci.yml
- build.cake
- src/TestEngine/testcentric.engine/Services/ExtensionService.cs
- src/TestEngine/testcentric.engine/testcentric.engine.csproj
- testcentric-engine.sln
> Add CI Workflow and update dependencies
